# Generated by Django 4.0.1 on 2022-01-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementsSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xPosition', models.DecimalField(decimal_places=3, max_digits=5)),
                ('yPosition', models.DecimalField(decimal_places=3, max_digits=5)),
                ('zPosition', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('xVelocity', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('yVelocity', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('zVelocity', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('xDimension', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('yDimension', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('zDimension', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('timestamp', models.IntegerField()),
                ('measurementsSet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restAPI.measurementssets')),
            ],
        ),
    ]
