# Generated by Django 4.0.1 on 2022-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.IntegerField()),
                ('xPosition', models.DecimalField(decimal_places=3, max_digits=5)),
                ('yPosition', models.DecimalField(decimal_places=3, max_digits=5)),
                ('zPosition', models.DecimalField(decimal_places=3, max_digits=5)),
                ('xVelocity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('yVelocity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('zVelocity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('xDimension', models.DecimalField(decimal_places=3, max_digits=5)),
                ('yDimension', models.DecimalField(decimal_places=3, max_digits=5)),
                ('zDimension', models.DecimalField(decimal_places=3, max_digits=5)),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
