# Generated by Django 4.0.1 on 2022-01-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementsSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.DecimalField(decimal_places=3, max_digits=5)),
                ('y_position', models.DecimalField(decimal_places=3, max_digits=5)),
                ('z_position', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('x_velocity', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('y_velocity', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('z_velocity', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('x_dimension', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('y_dimension', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('z_dimension', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('timestamp', models.IntegerField()),
                ('measurements_set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='restAPI.measurementssets')),
            ],
        ),
    ]
